name: Keepalive Workflow

on:
  schedule:
    # Runs every Tuesday at 00:00 UTC
    - cron: '0 0 * * 2'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true
          time_elapsed: 30
